### ISSUE TITLE
Problem with moineflayer on connecting

### ISSUE THREAD

**Issue by etiaro** [rob9315/mcproxy-old#17]
Hi, I am building an antiafk for 2bored2wait, using mcproxy, and I am sometimes getting crashes when connecting to the proxy and bot is performing some actions(I try to stop them, but it's asynchronous so sometimes something goes wrong). Usually happens when moving items in inventory in connected client, so i assume there are happening some differences in mineflayer inventory and client inventory. Any ideas how to fix that?

**Comment by etiaro** [comment]
here's sample error, maybe mineflayer update could handle this problem?




/home/****/2bored2wait/node_modules/minecraft-protocol/src/transforms/>
          } else { throw e }
                   ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(click.id <= actionId)

    at confirmTransaction (/home/etiaro/ETIARO/2bored2wait/node_modules/minefla>
    at Client.<anonymous> (/home/etiaro/ETIARO/2bored2wait/node_modules/minefla>
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (/home/etiaro/ETIARO/2bored2wait/node_modul>
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (/home/etiaro/ETIARO/2bored2wait/node_modules/protodef/node_mod>
    at readableAddChunk (/home/etiaro/ETIARO/2bored2wait/node_modules/protodef/>
    at FullPacketParser.Readable.push (/home/etiaro/ETIARO/2bored2wait/node_mod>
    at FullPacketParser.Transform.push (/home/etiaro/ETIARO/2bored2wait/node_mo>
    at FullPacketParser._transform (/home/etiaro/ETIARO/2bored2wait/node_module>
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by rob9315** [comment]
I don't think the mineflayer team has figured out yet how to fix the inventory desync. Was one of my biggest problems as well

**Comment by etiaro** [comment]
I did some workaround for the problem at antiafk, just not using them simultanously
